defaults: &defaults
  working_directory: ~/capital-http
  docker:
    - image: circleci/clojure:lein-2.8.1
  environment:
    LEIN_ROOT: "true"
    JVM_OPTS: -Xmx3200m

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: capital-http-deps-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: capital-http-deps-{{ checksum "project.clj" }}
      - run: lein do uberjar, pom
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: lein deploy-prepared

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          context: clojars
          requires:
            - build
          filters:
            branches:
              only: master
